public class ConsciousKitchen {
  // Instance Variables
  private List<String> tools = new List<String>();
  private List<String> appliances = new List<String>();
  // private List<Food> foodItems = new List<Food>();
  // private List<Worker> allWorkers = new List<Worker>();
  // private Worker chef = new Worker();
  public String name;
  private Integer noOfStaff;
  public List<Time> businessHours = new List<Time>();
}
